" settings
set number                      " Display line numbers beside buffer
set nocompatible                " Don't maintain compatibility with Vi.
set hidden                      " Allow buffer change w/o saving
set lazyredraw                  " Don't update while executing macros
set backspace=indent,eol,start  " Sane backspace behavior
set history=1000                " Remember last 1000 commands
set scrolloff=4                 " Keep at least 4 lines below cursor

" indentation
set expandtab
set shiftwidth=2
set softtabstop=2

" spellcheck settings
set spell spelllang=en_us       " Spellcheck us English
syntax spell toplevel           " Spellcheck syntax as well
set complete+=kspell
hi clear SpellBad
hi SpellBad cterm=underline ctermfg=red
hi clear SpellLocal
hi SpellLocal cterm=underline ctermfg=95

" Make CtrlP use ag for listing the files. Way faster and no useless files.
" dnf install the_silver_searcher
let g:ctrlp_user_command = 'ag %s -l --hidden --nocolor -g ""'
let g:ctrlp_use_caching = 0

" syntastic settings
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" start Tmux settings
" automatically rebalance windows on vim resize
autocmd VimResized * :wincmd =

" zoom a vim pane, <C-w>= to re-balance
nnoremap <leader>- :wincmd _<cr>:wincmd \|<cr>
nnoremap <leader>= :wincmd =<cr>

" end Tmux settings

" plugins
call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-sensible'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'tpope/vim-rails'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-commentary'
Plug 'scrooloose/syntastic'
Plug 'ntpeters/vim-better-whitespace'
Plug ''
" Add plugins to &runtimepath
call plug#end()

